<link rel="stylesheet" href="{{asset('public/css/bootstrap.min.css')}}">
<style>
body {
	font-family: 'nikosh', sans-serif; 
	-webkit-print-color-adjust: exact;
	color-adjust: exact;
	font-size:16px;
} 
</style> 

	<!-- Main content -->
	<section class="content">
		<div class="box-header with-border" style="text-align:justfy;text-justify: inter-word;text-align:center;">					 
			<table width="90%" align="center">
				<tr>
					<td width="10%" align="left" rowspan="4"><img src="<?php echo e(asset('public/cdip.png')); ?>" style="float:left;margin-top:0%;" width="70" ></td>
					<td align="center" width="90%" style="font-size:26px;">সেন্টার ফর ডেভেলপমেন্ট ইনোভেশন এন্ড প্র্যাকটিসেস (সিদীপ) </td>
				</tr>
				<tr>
					<td width="90%" align="center" style="font-size:17px;">Centre for Development Innovation and Practices (CDIP)</td>
				</tr>
				<tr>
					<td align="center">সিদীপ ভবন, হাউজ # ১৭, রোড # ১৩, পিসিকালচার হাউজিং সোসাইটি, শেখেরটেক, আদাবর, ঢাকা</td>
				</tr>
				<tr>
					<td align="center" style="font-size:12px;">web:www.cdipbd.org, Email:info@cdipbd.org, Phone:02-48118633,02-48118634</td>
				</tr>
			</table>
			<hr>
		</div>

		 <?php echo $date_bangla; ?><br><br>
		<?php echo $emp_name_eng; ?><br>
		আইডি নং - <?php echo $id_bangla; ?> <br>
		<?php echo $designation_bangla; ?><br>
		<?php echo $pre_br_name_bn; ?> ব্রাঞ্চ <br>
				
		<br><br>
		
		<strong>বিষয়: বদলি প্রসঙ্গে।</strong>
		<br><br>	
		জনাব,<br>
		আপনি সংস্থার  ‘<?php echo $pre_br_name_bn; ?>’ ব্রাঞ্চে ‘<?php echo $designation_bangla; ?>’ হিসেবে কর্মরত আছেন। সংস্থার বৃহত্তর স্বার্থে আগামী 
		<?php echo $br_date_bangla; ?> তারিখ থেকে আপনাকে একই পদে <?php echo $area_name_bn; ?>র আওতাধীন ‘<?php echo $br_name_bangla; ?> ব্রাঞ্চে’ বদলি করা হলো। <br><br>
		
		আপনি আপনার যাবতীয় দায়-দায়িত্ব <?php echo $br_ha_date_bangla; ?> তারিখের মধ্যে সংশ্লিষ্ট ব্রাঞ্চ ম্যানেজারের নিকট বুঝিয়ে দিয়ে যথাসময়ে বদলিকৃত কর্মস্থলে যোগদান করবেন।
		
		<br><br>
		আশা করি বদলিকৃত কর্মস্থলে অর্পিত দায়িত্ব সুষ্ঠভাবে পালনের মাধ্যমে সংস্থার ভাবমূর্তি প্রতিষ্ঠিত করতে সক্ষম হবেন।
		<br><br>
		<span>ধন্যবাদান্তে,  <span>
		<br>
		<br>

		
		<table>
			<tr>
				<td>নাম : <?php echo $login_emp_name; ?></td>
			</tr>
			<tr>
				<td>আইডি নং : <?php echo $login_emp_id; ?></td>
			</tr>
			<tr>
				<?php if($login_emp_user_type == 4) { ?>
				<td>এরিয়া ম্যানেজার</td>
				<?php } else if($login_emp_user_type == 3) { ?>
				<td>ডিস্ট্রিক্ট ম্যানেজার</td>
				<?php } ?>
			</tr>
			<tr>
				<?php if($login_emp_user_type == 4) { ?>
				<td><?php echo $login_br_ar_zo->area_name_bn; ?>।</td>
				<?php } else if($login_emp_user_type == 3) { ?>
				<td><?php echo $login_br_ar_zo->zone_name_bn; ?>।</td>
				<?php } ?>
			</tr>
		</table>
		
		
		<br>
		অনুলিপি:
		<br>
		
		<ul style="list-style: none;">
			<li>১. পরিচালক, মাইক্রোফিন্যান্স প্রোগ্রাম।</li>
			<?php if($login_emp_user_type == 4) { ?>
			<li>২. সংশ্লিষ্ট ডিস্ট্রিক্ট ম্যানেজার।</li>
			<?php } else if($login_emp_user_type == 3) { ?>
			<li>২. সংশ্লিষ্ট এরিয়া ম্যানেজারদ্বয়।</li>
			<?php } ?>
			<li>৩. সংশ্লিষ্ট ব্রাঞ্চ ম্যানেজারদ্বয়।</li>
			<li>৪. ব্যক্তিগত নথি। </li>
		</ul>
		<br>
		<br>
		<br>
		<span style="float:left;font-size:11px;">** (Letter Generated By : CDIP Human Resource Management Software)</span>
	</section> 
